### ISSUE TITLE
Wrong Nodes in seed.defichain.io

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#2702]
## Summary
The Node include 2 seeds to finding correct Nodes on the Blockchain, one of them has old information and maybe its the reason for the massive sync problems of the Desktop Wallet.

Addresses:  
          **45.33.76.249 no Node**
          **13.53.74.153 Port closed**
          172.104.63.159 Port closed
          _3.67.62.149 ok_
          _18.138.191.151 ok_
          _18.198.89.109 ok_
          **13.48.219.32 Port closed**
          **172.105.66.203 ====>> 3.2.8 <<====**
          **178.79.170.28 Port closed**
          _52.76.182.139 ok_
Aliases:  seed.defichain.io

From 10 Nodes only 4 correct, the other are not available or withVersion 3.2.8.

## Steps to Reproduce
Download Snapshot and sync or new install wallet.

**Comment by prasannavl** [comment]
The following should be resolved:

- 172.104.63.159
- 172.105.66.203
- 45.33.76.249

Rest, we'll see or kick out of seeds for soon. But could you elaborate on the sync problems with desktop wallet? Since if it was seed related it should have affected the node as well.

**Comment by prasannavl** [comment]
DNS records have been updated to the following:

```
18.198.89.109
3.67.62.149
52.76.182.139
18.138.191.151
172.105.66.203
172.104.63.159
45.33.76.249
```

TTL is 300s. 

Thanks for this @Stonygan. Appreciated. Not sure if the Desktop wallet issue is related, but the seeds should be better now.

**Comment by prasannavl** [comment]
Closing this, as all seeds have been functional since the last update.

**Comment by supervolot** [comment]
The desktop app still not work fine. 
in my debug i found:
2023-11-19T15:54:37Z Loading addresses from DNS seeds (could take a while)
2023-11-19T15:54:37Z 0 addresses found from DNS seeds
2023-11-19T15:54:37Z dnsseed thread exit
i now add the nodes in the console and now it look like that works

**Comment by prasannavl** [comment]
Could you let us know if this happens with defid as well?

**Comment by Stonygan** [comment]
Please check again the Seed. I am sure that this is one of the main reasons for the slow syncing or jumping to another chain. At least I hope so, because that would be the simplest solution.

172.104.63.159 <- Port closed
45.33.76.249:8555   **3462716**  00000409  70038 "/DeFiChain:4.0.1/"
172.105.66.203:8555  **3462716**  00000409  70038 "/DeFiChain:4.0.1/"

other nodes are fine.
